import { createSlice } from "@reduxjs/toolkit";

const initialValue = [
  {
    id: 1,
    name: "The Miracle Morning (Updated)",
    img: "./deals/about.jpg",
    text1: "30% off",
    text2: "Deal",
    newprice: "$13.98",
    oldprice: "$19.95",
    alt: "about",
  },
  {
    id: 2,
    name: "SHAPERS - 4MM Laminated Lock",
    img: "./deals/shapers.webp",
    text1: "7% off",
    text2: "Deal",
    newprice: "$12.85",
    oldprice: "$13.84",
    alt: "shapers",
  },
  {
    id: 3,
    name: "Alpine Swiss - RFID Protected",
    img: "./deals/alpine.jpeg",
    text1: "22% off",
    text2: "Deal",
    newprice: "$15.63",
    oldprice: "$19.99",
    alt: "alpine",
  },
  {
    id: 4,
    name: "Funko POP! Rides The Batman",
    img: "./deals/funko.jpg",
    text1: "37% off",
    text2: "Deal",
    newprice: "$17.33",
    oldprice: "$27.32",
    alt: "funko",
  },
  {
    id: 5,
    name: "Pacifica Beauty Curl Enhanced",
    img: "./deals/curl.jpg",
    text1: "15% off",
    text2: "Deal",
    newprice: "$10.19",
    oldprice: "$12.00",
    alt: "curl",
  },
  {
    id: 6,
    name: "Guide Book of US Coins 2022",
    img: "./deals/coins.jpg",
    text1: "20% off",
    text2: "Deal",
    newprice: "$14.36",
    oldprice: "$17.95",
    alt: "coins",
  },
  {
    id: 7,
    name: "TOPS 5 x 8 Legal Pads",
    img: "./deals/prism.webp",
    text1: "35% off",
    text2: "Deal",
    newprice: "$9.70",
    oldprice: "$14.99",
    alt: "prism",
  },
  {
    id: 8,
    name: "Pillow Pets Disney - Mickey",
    img: "./deals/pets.jpg",
    text1: "29% off",
    text2: "Deal",
    newprice: "$24.99",
    oldprice: "$34.99",
    alt: "pets",
  },
  {
    id: 9,
    name: "ProFoot Original Miracle Insole",
    img: "./deals/profoot.jpg",
    text1: "Deal",
    text2: " ",
    newprice: "$7.99 ",
    oldprice: " ",
    alt: "profoot",
  },
  {
    id: 10,
    name: "Quality Park Bulk Dab",
    img: "./deals/bulk.jpg",
    text1: "28% off",
    text2: "Deal",
    newprice: "$17.69",
    oldprice: "$24.46",
    alt: "bulk",
  },
  {
    id: 11,
    name: "Hydro Flask Travel Tumblers",
    img: "./deals/hydro.webp",
    text1: "13% off",
    text2: "Deal",
    newprice: "$34.95",
    oldprice: "$39.95",
    alt: "hydro",
  },
  {
    id: 12,
    name: "Fluke 233AKIT Remote Display",
    img: "./deals/fluke.webp",
    text1: "10% off",
    text2: "Deal",
    newprice: "$438.92",
    oldprice: "$487.74",
    alt: "fluke",
  },
];

const discountSlice = createSlice({
  name: "discount",
  initialState: initialValue,
  reducers: {},
});

export const getDiscount = (state) => state.discount;
export default discountSlice.reducer;
